package com.artmall.mapper;

import com.artmall.pojo.NewProjectAttachment;
import com.artmall.pojo.NewProjectAttachmentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface NewProjectAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    long countByExample(NewProjectAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int deleteByExample(NewProjectAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int insert(NewProjectAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int insertSelective(NewProjectAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    List<NewProjectAttachment> selectByExample(NewProjectAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") NewProjectAttachment record, @Param("example") NewProjectAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int updateByExample(@Param("record") NewProjectAttachment record, @Param("example") NewProjectAttachmentExample example);
}