package com.artmall.mapper;

import com.artmall.pojo.NewProject;
import com.artmall.pojo.NewProjectExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Mapper
@Repository
public interface NewProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    long countByExample(NewProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int deleteByExample(NewProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int insert(NewProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int insertSelective(NewProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    List<NewProject> selectByExample(NewProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    NewProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") NewProject record, @Param("example") NewProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int updateByExample(@Param("record") NewProject record, @Param("example") NewProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int updateByPrimaryKeySelective(NewProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    int updateByPrimaryKey(NewProject record);
}