package com.artmall.mapper;

import com.artmall.pojo.WorksComplaint;
import com.artmall.pojo.WorksComplaintExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface WorksComplaintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    long countByExample(WorksComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int deleteByExample(WorksComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int insert(WorksComplaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int insertSelective(WorksComplaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    List<WorksComplaint> selectByExample(WorksComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    WorksComplaint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorksComplaint record, @Param("example") WorksComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByExample(@Param("record") WorksComplaint record, @Param("example") WorksComplaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByPrimaryKeySelective(WorksComplaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_complaint
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByPrimaryKey(WorksComplaint record);
}