package com.artmall.mapper;

import com.artmall.pojo.WorksAttachment;
import com.artmall.pojo.WorksAttachmentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface WorksAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    long countByExample(WorksAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int deleteByExample(WorksAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int insert(WorksAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int insertSelective(WorksAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    List<WorksAttachment> selectByExample(WorksAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    WorksAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorksAttachment record, @Param("example") WorksAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByExample(@Param("record") WorksAttachment record, @Param("example") WorksAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByPrimaryKeySelective(WorksAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_attachment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByPrimaryKey(WorksAttachment record);
}