package com.artmall.mapper;

import com.artmall.pojo.WorksComment;
import com.artmall.pojo.WorksCommentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface WorksCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    long countByExample(WorksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int deleteByExample(WorksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int insert(WorksComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int insertSelective(WorksComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    List<WorksComment> selectByExample(WorksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    WorksComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorksComment record, @Param("example") WorksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByExample(@Param("record") WorksComment record, @Param("example") WorksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByPrimaryKeySelective(WorksComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    int updateByPrimaryKey(WorksComment record);
}