package com.artmall.pojo;

import org.springframework.stereotype.Repository;

import java.util.Date;
@Repository
public class NewProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.business_id
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Long business_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private String project_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_description
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private String project_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.is_verified
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Byte is_verified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.budget
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Long budget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.tender_period
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Integer tender_period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.expected_time
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Integer expected_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.finish_time
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Date finish_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmt_create
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Date gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmt_modified
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private Date gmt_modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.skill
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    private String skill;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.business_id
     *
     * @return the value of project.business_id
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Long getBusiness_id() {
        return business_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.business_id
     *
     * @param business_id the value for project.business_id
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setBusiness_id(Long business_id) {
        this.business_id = business_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public String getProject_name() {
        return project_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param project_name the value for project.project_name
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setProject_name(String project_name) {
        this.project_name = project_name == null ? null : project_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_description
     *
     * @return the value of project.project_description
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public String getProject_description() {
        return project_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_description
     *
     * @param project_description the value for project.project_description
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setProject_description(String project_description) {
        this.project_description = project_description == null ? null : project_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.is_verified
     *
     * @return the value of project.is_verified
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Byte getIs_verified() {
        return is_verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.is_verified
     *
     * @param is_verified the value for project.is_verified
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setIs_verified(Byte is_verified) {
        this.is_verified = is_verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.budget
     *
     * @return the value of project.budget
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Long getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.budget
     *
     * @param budget the value for project.budget
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setBudget(Long budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.tender_period
     *
     * @return the value of project.tender_period
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Integer getTender_period() {
        return tender_period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.tender_period
     *
     * @param tender_period the value for project.tender_period
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setTender_period(Integer tender_period) {
        this.tender_period = tender_period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.expected_time
     *
     * @return the value of project.expected_time
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Integer getExpected_time() {
        return expected_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.expected_time
     *
     * @param expected_time the value for project.expected_time
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setExpected_time(Integer expected_time) {
        this.expected_time = expected_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.finish_time
     *
     * @return the value of project.finish_time
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Date getFinish_time() {
        return finish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.finish_time
     *
     * @param finish_time the value for project.finish_time
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setFinish_time(Date finish_time) {
        this.finish_time = finish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.gmt_create
     *
     * @return the value of project.gmt_create
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.gmt_create
     *
     * @param gmt_create the value for project.gmt_create
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.gmt_modified
     *
     * @return the value of project.gmt_modified
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.gmt_modified
     *
     * @param gmt_modified the value for project.gmt_modified
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.skill
     *
     * @return the value of project.skill
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public String getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.skill
     *
     * @param skill the value for project.skill
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setSkill(String skill) {
        this.skill = skill == null ? null : skill.trim();
    }
}