package com.artmall.pojo;

import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
@Repository
public class NewProjectAttachmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public NewProjectAttachmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameIsNull() {
            addCriterion("attachment_name is null");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameIsNotNull() {
            addCriterion("attachment_name is not null");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameEqualTo(String value) {
            addCriterion("attachment_name =", value, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameNotEqualTo(String value) {
            addCriterion("attachment_name <>", value, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameGreaterThan(String value) {
            addCriterion("attachment_name >", value, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameGreaterThanOrEqualTo(String value) {
            addCriterion("attachment_name >=", value, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameLessThan(String value) {
            addCriterion("attachment_name <", value, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameLessThanOrEqualTo(String value) {
            addCriterion("attachment_name <=", value, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameLike(String value) {
            addCriterion("attachment_name like", value, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameNotLike(String value) {
            addCriterion("attachment_name not like", value, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameIn(List<String> values) {
            addCriterion("attachment_name in", values, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameNotIn(List<String> values) {
            addCriterion("attachment_name not in", values, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameBetween(String value1, String value2) {
            addCriterion("attachment_name between", value1, value2, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_nameNotBetween(String value1, String value2) {
            addCriterion("attachment_name not between", value1, value2, "attachment_name");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathIsNull() {
            addCriterion("attachment_path is null");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathIsNotNull() {
            addCriterion("attachment_path is not null");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathEqualTo(String value) {
            addCriterion("attachment_path =", value, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathNotEqualTo(String value) {
            addCriterion("attachment_path <>", value, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathGreaterThan(String value) {
            addCriterion("attachment_path >", value, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathGreaterThanOrEqualTo(String value) {
            addCriterion("attachment_path >=", value, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathLessThan(String value) {
            addCriterion("attachment_path <", value, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathLessThanOrEqualTo(String value) {
            addCriterion("attachment_path <=", value, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathLike(String value) {
            addCriterion("attachment_path like", value, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathNotLike(String value) {
            addCriterion("attachment_path not like", value, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathIn(List<String> values) {
            addCriterion("attachment_path in", values, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathNotIn(List<String> values) {
            addCriterion("attachment_path not in", values, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathBetween(String value1, String value2) {
            addCriterion("attachment_path between", value1, value2, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_pathNotBetween(String value1, String value2) {
            addCriterion("attachment_path not between", value1, value2, "attachment_path");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeIsNull() {
            addCriterion("attachment_size is null");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeIsNotNull() {
            addCriterion("attachment_size is not null");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeEqualTo(Long value) {
            addCriterion("attachment_size =", value, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeNotEqualTo(Long value) {
            addCriterion("attachment_size <>", value, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeGreaterThan(Long value) {
            addCriterion("attachment_size >", value, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeGreaterThanOrEqualTo(Long value) {
            addCriterion("attachment_size >=", value, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeLessThan(Long value) {
            addCriterion("attachment_size <", value, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeLessThanOrEqualTo(Long value) {
            addCriterion("attachment_size <=", value, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeIn(List<Long> values) {
            addCriterion("attachment_size in", values, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeNotIn(List<Long> values) {
            addCriterion("attachment_size not in", values, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeBetween(Long value1, Long value2) {
            addCriterion("attachment_size between", value1, value2, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andAttachment_sizeNotBetween(Long value1, Long value2) {
            addCriterion("attachment_size not between", value1, value2, "attachment_size");
            return (Criteria) this;
        }

        public Criteria andProject_idIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProject_idIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProject_idEqualTo(Long value) {
            addCriterion("project_id =", value, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idNotEqualTo(Long value) {
            addCriterion("project_id <>", value, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idGreaterThan(Long value) {
            addCriterion("project_id >", value, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idGreaterThanOrEqualTo(Long value) {
            addCriterion("project_id >=", value, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idLessThan(Long value) {
            addCriterion("project_id <", value, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idLessThanOrEqualTo(Long value) {
            addCriterion("project_id <=", value, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idIn(List<Long> values) {
            addCriterion("project_id in", values, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idNotIn(List<Long> values) {
            addCriterion("project_id not in", values, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idBetween(Long value1, Long value2) {
            addCriterion("project_id between", value1, value2, "project_id");
            return (Criteria) this;
        }

        public Criteria andProject_idNotBetween(Long value1, Long value2) {
            addCriterion("project_id not between", value1, value2, "project_id");
            return (Criteria) this;
        }

        public Criteria andGmt_createIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmt_createIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmt_createEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmt_modified");
            return (Criteria) this;
        }

        public Criteria andGmt_modifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmt_modified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_attachment
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 09 16:22:42 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_attachment
     *
     * @mbg.generated Sun Sep 09 16:22:42 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}