package com.artmall.pojo;

import org.springframework.stereotype.Repository;

import java.util.Date;
@Repository
public class Works {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.student_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long student_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_name
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private String works_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_describe
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private String works_describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_status
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Byte works_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.price
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Date gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Date gmt_modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.follower_count
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Integer follower_count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.id
     *
     * @return the value of works.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.id
     *
     * @param id the value for works.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.student_id
     *
     * @return the value of works.student_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getStudent_id() {
        return student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.student_id
     *
     * @param student_id the value for works.student_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setStudent_id(Long student_id) {
        this.student_id = student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_name
     *
     * @return the value of works.works_name
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public String getWorks_name() {
        return works_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_name
     *
     * @param works_name the value for works.works_name
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setWorks_name(String works_name) {
        this.works_name = works_name == null ? null : works_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_describe
     *
     * @return the value of works.works_describe
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public String getWorks_describe() {
        return works_describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_describe
     *
     * @param works_describe the value for works.works_describe
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setWorks_describe(String works_describe) {
        this.works_describe = works_describe == null ? null : works_describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_status
     *
     * @return the value of works.works_status
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Byte getWorks_status() {
        return works_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_status
     *
     * @param works_status the value for works.works_status
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setWorks_status(Byte works_status) {
        this.works_status = works_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.price
     *
     * @return the value of works.price
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.price
     *
     * @param price the value for works.price
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.gmt_create
     *
     * @return the value of works.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.gmt_create
     *
     * @param gmt_create the value for works.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.gmt_modified
     *
     * @return the value of works.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.gmt_modified
     *
     * @param gmt_modified the value for works.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.follower_count
     *
     * @return the value of works.follower_count
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Integer getFollower_count() {
        return follower_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.follower_count
     *
     * @param follower_count the value for works.follower_count
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setFollower_count(Integer follower_count) {
        this.follower_count = follower_count;
    }
}