package com.artmall.pojo;

import org.springframework.stereotype.Repository;

import java.util.Date;
@Repository
public class WorksComplaint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_complaint.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_complaint.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long works_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_complaint.complaint_description
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private String complaint_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_complaint.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Date gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_complaint.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Date gmt_modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_complaint.id
     *
     * @return the value of works_complaint.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_complaint.id
     *
     * @param id the value for works_complaint.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_complaint.works_id
     *
     * @return the value of works_complaint.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getWorks_id() {
        return works_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_complaint.works_id
     *
     * @param works_id the value for works_complaint.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setWorks_id(Long works_id) {
        this.works_id = works_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_complaint.complaint_description
     *
     * @return the value of works_complaint.complaint_description
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public String getComplaint_description() {
        return complaint_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_complaint.complaint_description
     *
     * @param complaint_description the value for works_complaint.complaint_description
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setComplaint_description(String complaint_description) {
        this.complaint_description = complaint_description == null ? null : complaint_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_complaint.gmt_create
     *
     * @return the value of works_complaint.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_complaint.gmt_create
     *
     * @param gmt_create the value for works_complaint.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_complaint.gmt_modified
     *
     * @return the value of works_complaint.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_complaint.gmt_modified
     *
     * @param gmt_modified the value for works_complaint.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }
}