package com.artmall.pojo;

import org.springframework.stereotype.Repository;

import java.util.Date;
@Repository
public class WorksAttachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_attachment.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_attachment.attachment_name
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private String attachment_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_attachment.attachment_path
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private String attachment_path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_attachment.attachment_size
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long attachment_size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_attachment.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long works_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_attachment.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Date gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_attachment.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Date gmt_modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_attachment.id
     *
     * @return the value of works_attachment.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_attachment.id
     *
     * @param id the value for works_attachment.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_attachment.attachment_name
     *
     * @return the value of works_attachment.attachment_name
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public String getAttachment_name() {
        return attachment_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_attachment.attachment_name
     *
     * @param attachment_name the value for works_attachment.attachment_name
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setAttachment_name(String attachment_name) {
        this.attachment_name = attachment_name == null ? null : attachment_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_attachment.attachment_path
     *
     * @return the value of works_attachment.attachment_path
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public String getAttachment_path() {
        return attachment_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_attachment.attachment_path
     *
     * @param attachment_path the value for works_attachment.attachment_path
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setAttachment_path(String attachment_path) {
        this.attachment_path = attachment_path == null ? null : attachment_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_attachment.attachment_size
     *
     * @return the value of works_attachment.attachment_size
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getAttachment_size() {
        return attachment_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_attachment.attachment_size
     *
     * @param attachment_size the value for works_attachment.attachment_size
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setAttachment_size(Long attachment_size) {
        this.attachment_size = attachment_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_attachment.works_id
     *
     * @return the value of works_attachment.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getWorks_id() {
        return works_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_attachment.works_id
     *
     * @param works_id the value for works_attachment.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setWorks_id(Long works_id) {
        this.works_id = works_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_attachment.gmt_create
     *
     * @return the value of works_attachment.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_attachment.gmt_create
     *
     * @param gmt_create the value for works_attachment.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_attachment.gmt_modified
     *
     * @return the value of works_attachment.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_attachment.gmt_modified
     *
     * @param gmt_modified the value for works_attachment.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }
}