package com.artmall.pojo;

import org.springframework.stereotype.Repository;

import java.util.Date;
@Repository
public class WorksComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_comment.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_comment.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Date gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_comment.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Date gmt_modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_comment.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long works_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_comment.user_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_comment.comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_comment.id
     *
     * @return the value of works_comment.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_comment.id
     *
     * @param id the value for works_comment.id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_comment.gmt_create
     *
     * @return the value of works_comment.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_comment.gmt_create
     *
     * @param gmt_create the value for works_comment.gmt_create
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_comment.gmt_modified
     *
     * @return the value of works_comment.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_comment.gmt_modified
     *
     * @param gmt_modified the value for works_comment.gmt_modified
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_comment.works_id
     *
     * @return the value of works_comment.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getWorks_id() {
        return works_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_comment.works_id
     *
     * @param works_id the value for works_comment.works_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setWorks_id(Long works_id) {
        this.works_id = works_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_comment.user_id
     *
     * @return the value of works_comment.user_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_comment.user_id
     *
     * @param user_id the value for works_comment.user_id
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_comment.comment
     *
     * @return the value of works_comment.comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_comment.comment
     *
     * @param comment the value for works_comment.comment
     *
     * @mbg.generated Mon Sep 10 16:53:51 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}